todo_app/models.py
from flask_login import UserMixin

import sqlalchemy as sa
import sqlalchemy.orm as so
from werkzeug.security import generate_password_hash, \
    check_password_hash
from typing import Optional
from datetime import datetime, timezone

from todo_app import db, login_manager


class User(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    email: so.Mapped[int] = so.mapped_column(sa.String(64), index=True, 
                                            unique=True, nullable=False)
    password_hash: so.Mapped[str] = so.mapped_column(sa.String(256),
                                                    nullable=False,
                                                    index=True)
    
    tasks: so.WriteOnlyMapped['Task'] = so.relationship(back_populates='author')

    
    def __repr__(self):
        return f'<User: id={self.id}; email={self.email}'
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(id):
    return db.session.get(User, int(id))

class Task(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    title: so.Mapped[str] = so.mapped_column(sa.String(64), index=True,
                                             nullable=False)
    description: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256),
                                                             index=True)
    created_at: so.Mapped[datetime] = so.mapped_column(index=True,
                                default=lambda: datetime.now(timezone.utc))
    completed: so.Mapped[bool] = so.mapped_column(default=False)

    user_id: so.Mapped[User] = so.mapped_column(sa.ForeignKey(User.id),
                                                index=True)
    
    author: so.Mapped['User'] = so.relationship(back_populates='tasks')


    def __repr__(self):
        return f'Post: id={self.id}; title={self.title}'

todo_app/main/forms.py
from flask_wtf import FlaskForm

from wtforms import TextAreaField,StringField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
import sqlalchemy as sa

from todo_app import db
from todo_app.models import User


class CreateTaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), 
                                             Length(min=1, max=64)])
    description = TextAreaField('Description', validators=[Length(max=256)])
    submit = SubmitField('Create')

class EditTaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), 
                                             Length(min=1, max=64)])
    description = TextAreaField('Description', validators=[Length(max=256)])
    completed = BooleanField('Completed')
    submit = SubmitField('Edit')

todo_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect

from config import Config


db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.login_message ="Please login to access this page"
csrf = CSRFProtect()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    csrf.init_app(app)

    from todo_app.main import main_bp
    app.register_blueprint(main_bp)

    from todo_app.auth import auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from todo_app.errors import errors_bp
    app.register_blueprint(errors_bp)


    return app

from todo_app import models

todo_app/main/__init__.py
from flask import Blueprint


main_bp = Blueprint('main', __name__)

from todo_app.main import routes

todo_app/main/routes.py
from flask import render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required

import sqlalchemy as sa

from todo_app import db
from todo_app.main import main_bp
from todo_app.main.forms import CreateTaskForm, EditTaskForm
from todo_app.models import Task


@main_bp.route('/')
@main_bp.route('/index')
def index():
    return render_template('main/index.html')


@main_bp.route('/todolist')
@login_required
def todolist():
    tasks = db.session.scalars(
        current_user.tasks.select().order_by(Task.completed)
    ).all()
    return render_template('main/todolist.html', tasks=tasks)

@main_bp.route('/create_task', methods=['GET', 'POST'])
@login_required
def create_task():
    form = CreateTaskForm()
    if form.validate_on_submit():
        task = Task(title=form.title.data, description=form.description.data, 
                    author=current_user)
        db.session.add(task)
        db.session.commit()
        flash("You have successfully create the task")

        return redirect(url_for('main.todolist'))

    return render_template('main/create_task.html', form=form)

@main_bp.route('/edit_task/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_task(id):
    task = db.session.get(Task, id)

    if task is not None and task.author == current_user:
        # Reuse CreateTaskForm for editing task
        form = EditTaskForm()
        if form.validate_on_submit():
            task.title = form.title.data
            task.description = form.description.data
            task.completed = form.completed.data
            db.session.commit()
            flash("You have successfully edit the task")

            return redirect(url_for('main.todolist'))
        elif request.method == 'GET':
            form.title.data = task.title
            form.description.data = task.description
    else:
        flash("You don't have a permission")
        return redirect(url_for('main.todolist'))

    return render_template('main/edit_task.html', form=form)

@main_bp.route('/delete_task/<int:id>', methods=("POST", ))
@login_required
def delete_task(id):
    task = db.session.get(Task, id)
    if task is not None and task.author == current_user:
        db.session.delete(task)
        db.session.commit()
        flash("You have successfully deleted the task")
    else:
        flash("You don't have a permission")
    return redirect(url_for('main.todolist'))

@main_bp.route("/edit_task_status/<int:id>", methods=("POST", ))
@login_required
def edit_task_status(id):
    task = db.session.get(Task, id)
    if task is not None and task.author == current_user:
        task.completed = not task.completed
        db.session.commit()
    else:
        flash("You don't have a permission")
    return redirect(url_for("main.todolist"))

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body data-bs-theme="dark">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('static', filename='monkey.jpg') }}" alt="" width="50" height="50" class="d-inline-block">
            ToDo App
          </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.todolist') }}">Todolist</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
              </li>
              {% endif %}
          </div>
        </div>
    </nav>
    <div class="mx-auto p-3">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dark alert-dismissible" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

todo_app/templates/main/create_task.html
{% extends 'base.html' %}

{% block content %}
<h3><a href="{{ url_for('main.todolist') }}">Back to Todolist</a></h3>
<p><h2>Create Task</h2></p>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.title.label(class="form-label") }}
        {{ form.title(size=64, class="form-control") }}
        {% for error in form.title.errors %}
        <p class="alert alert-danger alert-dismissible">Error: {{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        <p>{{ form.description.label(class="form-label") }}</p>
        {{ form.description(cols=24, rows=12, class="form-control") }}
        {% for error in form.description.errors %}
        <p class="alert alert-danger alert-dismissible">Error: {{ error }}</p>
        {% endfor %}
    </div>
    <div>
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

todo_app/templates/main/edit_task.html
{% extends 'base.html' %}

{% block content %}
<h3><a href="{{ url_for('main.todolist') }}">Back to Todolist</a></h3>
<p><h2>Edit Task</h2></p>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.title.label(class="form-label") }}
        {{ form.title(size=64, class="form-control") }}
        {% for error in form.title.errors %}
        <p class="alert alert-danger" >Error: {{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        <p>{{ form.description.label(class="form-label") }}</p>
        {{ form.description(cols=24, rows=8, class="form-control") }}
        {% for error in form.description.errors %}
        <p class="alert alert-danger">Error: {{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.completed.label(class="form-check-label") }}
        {{ form.completed(class="form-check-input") }}
    </div>
    <p>
        {{ form.submit(class="btn btn-primary") }}
    </p>
</form>
{% endblock %}

todo_app/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
<h1>ToDo List</h1>
<p>Index page</p>
{% endblock %}

todo_app/templates/main/todolist.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mb-4">ToDo List</h1>

<a class="btn btn-primary" href="{{ url_for('main.create_task') }}">Create Task</a>

<table class="table table-hover text-center">
    <thead>
      <tr>
        <th scope="col">Task</th>
        <th scope="col">Completed</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
      <tr>
        <td>{{ task.title[0:15] }}</td>
        <td>
          <form action="{{ url_for('main.edit_task_status', id=task.id) }}" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="checkbox" class="form-check-input" {% if task.completed %} checked{% endif %}
              name="status_task" onchange="this.form.submit()">
          </form>
        </td>
        <td>
          <a class="btn btn-secondary" href="{{ url_for('main.edit_task', id=task.id) }}">Edit</a>
        </td>
        <td>
          <form action="{{ url_for('main.delete_task', id=task.id) }}" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type="submit" class="btn btn-warning">Delete</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}